CREATE VIEW @extschema@.ccp_backrest_last_diff_backup AS SELECT * FROM pgm_backrest_last_diff_backup;
CREATE VIEW @extschema@.ccp_backrest_last_full_backup AS SELECT * FROM pgm_backrest_last_full_backup;
CREATE VIEW @extschema@.ccp_backrest_last_incr_backup AS SELECT * FROM pgm_backrest_last_incr_backup;
CREATE VIEW @extschema@.ccp_backrest_last_info AS SELECT * FROM pgm_backrest_last_info;
CREATE VIEW @extschema@.ccp_backrest_oldest_full_backup AS SELECT * FROM pgm_backrest_oldest_full_backup; 
CREATE VIEW @extschema@.ccp_archive_command_status AS SELECT * FROM pgm_archive_command_status;
CREATE VIEW @extschema@.ccp_connection_stats AS SELECT * FROM pgm_connection_stats;
CREATE VIEW @extschema@.ccp_data_checksum_failure AS SELECT * FROM pgm_data_checksum_failure; 
CREATE VIEW @extschema@.ccp_database_size AS SELECT * FROM pgm_database_size;
CREATE VIEW @extschema@.ccp_locks AS SELECT * FROM pgm_locks;
CREATE VIEW @extschema@.ccp_pg_is_in_recovery AS SELECT * FROM pgm_pg_is_in_recovery;
CREATE VIEW @extschema@.ccp_pg_stat_statements_reset AS SELECT * FROM pgm_pg_stat_statements_reset;
CREATE VIEW @extschema@.ccp_postgresql_version AS SELECT * FROM pgm_postgresql_version;
CREATE VIEW @extschema@.ccp_postmaster_runtime AS SELECT * FROM pgm_postmaster_runtime;
CREATE VIEW @extschema@.ccp_postmaster_uptime AS SELECT * FROM pgm_postmaster_uptime;
CREATE VIEW @extschema@.ccp_replication_lag AS SELECT * FROM pgm_replication_lag;
CREATE VIEW @extschema@.ccp_replication_lag_size AS SELECT * FROM pgm_replication_lag_size;
CREATE VIEW @extschema@.ccp_replication_slots AS SELECT * FROM pgm_replication_slots;
CREATE VIEW @extschema@.ccp_settings_pending_restart AS SELECT * FROM pgm_settings_pending_restart; 
CREATE VIEW @extschema@.ccp_stat_bgwriter AS SELECT * FROM pgm_stat_bgwriter;
CREATE VIEW @extschema@.ccp_stat_checkpointer AS SELECT * FROM pgm_stat_checkpointer;
CREATE VIEW @extschema@.ccp_stat_database AS SELECT * FROM pgm_stat_database;
CREATE VIEW @extschema@.ccp_stat_io_bgwriter AS SELECT * FROM pgm_stat_io_bgwriter;
CREATE VIEW @extschema@.ccp_stat_user_tables AS SELECT * FROM pgm_stat_user_tables;
CREATE VIEW @extschema@.ccp_table_size AS SELECT * FROM pgm_table_size;
CREATE VIEW @extschema@.ccp_transaction_wraparound AS SELECT * FROM pgm_transaction_wraparound;
CREATE VIEW @extschema@.ccp_wal_activity AS SELECT * FROM pgm_wal_activity;


COMMENT ON VIEW @extschema@.ccp_backrest_last_diff_backup IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_backrest_last_full_backup IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_backrest_last_incr_backup IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_backrest_last_info IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_backrest_oldest_full_backup IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_archive_command_status IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_connection_stats IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_data_checksum_failure IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_database_size IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_locks IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_pg_is_in_recovery IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_pg_stat_statements_reset IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_postgresql_version IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_postmaster_runtime IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_postmaster_uptime IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_replication_lag IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_replication_lag_size IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_replication_slots IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_settings_pending_restart IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_stat_bgwriter IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_stat_checkpointer IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_stat_database IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_stat_io_bgwriter IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_stat_user_tables IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_table_size IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_transaction_wraparound IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';
COMMENT ON VIEW @extschema@.ccp_wal_activity IS 'This object exists for backward compatibility with applications that are expecting object names from version 2.x and older. Please update your applications to use the new object names introduced in 3.0.0';

